### ISSUE TITLE
Is AWS Cloud Design Pattern suitable for 'style guide'?

### ISSUE THREAD

**Issue by namse** [kciter/awesome-style-guide#7]
I read that CDP(Cloud Design Pattern) and thought 'is it really suitable to say 'style-guide''?.

The style guide is one of the rule to coding, to make better productivity, I think.
But the 'Design Pattern' is a kind of reusable solutions which commonly occur.

So why don't we remove AWS Cloud Design Pattern and other Design Pattern things in this repository?

**Comment by kciter** [comment]
Hello, @skatpgusskat
I think **style-guide** is not only Programming Languages code style guide but also **Architecture**, Platforms, Frameworks.
